#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/sbin/s12-pro-signald"
    procd_close_instance
}

stop_service() {
  for KILLPID in `ps | grep s12-pro-signald | awk '{print $1;exit}'`; do
    kill -9 $KILLPID >/dev/null
  done
  sleep 1
  return 0
}

restart_service() {
    stop_service
    start_service
}
